export const GAME_CATALOG = [
  { slug: "valorant", name: "Valorant", genre: "Tactical Shooter" },
  { slug: "counter-strike-2", name: "Counter-Strike 2", genre: "Tactical Shooter" },
  { slug: "league-of-legends", name: "League of Legends", genre: "MOBA" },
  { slug: "fortnite", name: "Fortnite", genre: "Battle Royale" },
  { slug: "apex-legends", name: "Apex Legends", genre: "Battle Royale" },
  { slug: "call-of-duty-warzone", name: "Call of Duty / Warzone", genre: "Shooter" },
  { slug: "rainbow-six-siege", name: "Rainbow Six Siege", genre: "Tactical Shooter" },
  { slug: "overwatch-2", name: "Overwatch 2", genre: "Hero Shooter" },
  { slug: "rocket-league", name: "Rocket League", genre: "Sports" },
  { slug: "minecraft", name: "Minecraft", genre: "Sandbox" },
  { slug: "gta-online", name: "GTA Online", genre: "Open World" },
  { slug: "pubg", name: "PUBG", genre: "Battle Royale" },
  { slug: "destiny-2", name: "Destiny 2", genre: "Looter Shooter" },
  { slug: "dota-2", name: "Dota 2", genre: "MOBA" },
  { slug: "world-of-warcraft", name: "World of Warcraft", genre: "MMO" },
  { slug: "escape-from-tarkov", name: "Escape from Tarkov", genre: "Extraction Shooter" },
  { slug: "rust", name: "Rust", genre: "Survival" },
  { slug: "ea-sports-fc", name: "FIFA / EA Sports FC", genre: "Sports" },
  { slug: "dead-by-daylight", name: "Dead by Daylight", genre: "Horror" },
  { slug: "marvel-rivals", name: "Marvel Rivals", genre: "Hero Shooter" },
] as const;

export const PLAYSTYLE_TAGS = [
  "Competitive",
  "Casual",
  "Chill",
  "Tryhard",
  "Mic Required",
  "Shotcaller",
  "Beginner Friendly",
  "Rank Grind",
  "Late Night",
  "Weekend Warrior",
] as const;

export const LANGUAGE_OPTIONS = [
  "English",
  "Spanish",
  "French",
  "German",
  "Portuguese",
  "Italian",
  "Norwegian",
  "Swedish",
  "Danish",
  "Polish",
] as const;

export const REGION_OPTIONS = [
  "North America",
  "Europe West",
  "Europe Nordic",
  "South America",
  "Middle East",
  "Asia Pacific",
  "Oceania",
] as const;

export const PLAYTIME_OPTIONS = [
  "Weekday evenings",
  "Late nights",
  "Weekend mornings",
  "Weekend evenings",
  "Flexible",
] as const;

export const GAME_RANKS = {
  valorant: [
    "Unranked",
    "Iron 1",
    "Iron 2",
    "Iron 3",
    "Bronze 1",
    "Bronze 2",
    "Bronze 3",
    "Silver 1",
    "Silver 2",
    "Silver 3",
    "Gold 1",
    "Gold 2",
    "Gold 3",
    "Platinum 1",
    "Platinum 2",
    "Platinum 3",
    "Diamond 1",
    "Diamond 2",
    "Diamond 3",
    "Ascendant 1",
    "Ascendant 2",
    "Ascendant 3",
    "Immortal 1",
    "Immortal 2",
    "Immortal 3",
    "Radiant",
  ],
  "counter-strike-2": [
    "Unranked",
    "0-4,999 CS Rating",
    "5,000-9,999 CS Rating",
    "10,000-14,999 CS Rating",
    "15,000-19,999 CS Rating",
    "20,000-24,999 CS Rating",
    "25,000-29,999 CS Rating",
    "30,000+ CS Rating",
  ],
  "league-of-legends": [
    "Unranked",
    "Iron IV",
    "Iron III",
    "Iron II",
    "Iron I",
    "Bronze IV",
    "Bronze III",
    "Bronze II",
    "Bronze I",
    "Silver IV",
    "Silver III",
    "Silver II",
    "Silver I",
    "Gold IV",
    "Gold III",
    "Gold II",
    "Gold I",
    "Platinum IV",
    "Platinum III",
    "Platinum II",
    "Platinum I",
    "Emerald IV",
    "Emerald III",
    "Emerald II",
    "Emerald I",
    "Diamond IV",
    "Diamond III",
    "Diamond II",
    "Diamond I",
    "Master",
    "Grandmaster",
    "Challenger",
  ],
  fortnite: [
    "Unranked",
    "Bronze I",
    "Bronze II",
    "Bronze III",
    "Silver I",
    "Silver II",
    "Silver III",
    "Gold I",
    "Gold II",
    "Gold III",
    "Platinum I",
    "Platinum II",
    "Platinum III",
    "Diamond I",
    "Diamond II",
    "Diamond III",
    "Elite",
    "Champion",
    "Unreal",
  ],
  "apex-legends": [
    "Unranked",
    "Rookie IV",
    "Rookie III",
    "Rookie II",
    "Rookie I",
    "Bronze IV",
    "Bronze III",
    "Bronze II",
    "Bronze I",
    "Silver IV",
    "Silver III",
    "Silver II",
    "Silver I",
    "Gold IV",
    "Gold III",
    "Gold II",
    "Gold I",
    "Platinum IV",
    "Platinum III",
    "Platinum II",
    "Platinum I",
    "Diamond IV",
    "Diamond III",
    "Diamond II",
    "Diamond I",
    "Master",
    "Apex Predator",
  ],
  "call-of-duty-warzone": [
    "Unranked",
    "Bronze I",
    "Bronze II",
    "Bronze III",
    "Silver I",
    "Silver II",
    "Silver III",
    "Gold I",
    "Gold II",
    "Gold III",
    "Platinum I",
    "Platinum II",
    "Platinum III",
    "Diamond I",
    "Diamond II",
    "Diamond III",
    "Crimson I",
    "Crimson II",
    "Crimson III",
    "Iridescent",
    "Top 250",
  ],
  "rainbow-six-siege": [
    "Unranked",
    "Copper V",
    "Copper IV",
    "Copper III",
    "Copper II",
    "Copper I",
    "Bronze V",
    "Bronze IV",
    "Bronze III",
    "Bronze II",
    "Bronze I",
    "Silver V",
    "Silver IV",
    "Silver III",
    "Silver II",
    "Silver I",
    "Gold V",
    "Gold IV",
    "Gold III",
    "Gold II",
    "Gold I",
    "Platinum V",
    "Platinum IV",
    "Platinum III",
    "Platinum II",
    "Platinum I",
    "Emerald V",
    "Emerald IV",
    "Emerald III",
    "Emerald II",
    "Emerald I",
    "Diamond V",
    "Diamond IV",
    "Diamond III",
    "Diamond II",
    "Diamond I",
    "Champion",
  ],
  "overwatch-2": [
    "Unranked",
    "Bronze 5",
    "Bronze 4",
    "Bronze 3",
    "Bronze 2",
    "Bronze 1",
    "Silver 5",
    "Silver 4",
    "Silver 3",
    "Silver 2",
    "Silver 1",
    "Gold 5",
    "Gold 4",
    "Gold 3",
    "Gold 2",
    "Gold 1",
    "Platinum 5",
    "Platinum 4",
    "Platinum 3",
    "Platinum 2",
    "Platinum 1",
    "Diamond 5",
    "Diamond 4",
    "Diamond 3",
    "Diamond 2",
    "Diamond 1",
    "Master 5",
    "Master 4",
    "Master 3",
    "Master 2",
    "Master 1",
    "Grandmaster 5",
    "Grandmaster 4",
    "Grandmaster 3",
    "Grandmaster 2",
    "Grandmaster 1",
    "Champion 5",
    "Champion 4",
    "Champion 3",
    "Champion 2",
    "Champion 1",
    "Top 500",
  ],
  "rocket-league": [
    "Unranked",
    "Bronze I",
    "Bronze II",
    "Bronze III",
    "Silver I",
    "Silver II",
    "Silver III",
    "Gold I",
    "Gold II",
    "Gold III",
    "Platinum I",
    "Platinum II",
    "Platinum III",
    "Diamond I",
    "Diamond II",
    "Diamond III",
    "Champion I",
    "Champion II",
    "Champion III",
    "Grand Champion I",
    "Grand Champion II",
    "Grand Champion III",
    "Supersonic Legend",
  ],
  minecraft: ["Unranked"],
  "gta-online": ["Unranked"],
  pubg: [
    "Unranked",
    "Bronze V",
    "Bronze IV",
    "Bronze III",
    "Bronze II",
    "Bronze I",
    "Silver V",
    "Silver IV",
    "Silver III",
    "Silver II",
    "Silver I",
    "Gold V",
    "Gold IV",
    "Gold III",
    "Gold II",
    "Gold I",
    "Platinum V",
    "Platinum IV",
    "Platinum III",
    "Platinum II",
    "Platinum I",
    "Diamond V",
    "Diamond IV",
    "Diamond III",
    "Diamond II",
    "Diamond I",
    "Master V",
    "Master IV",
    "Master III",
    "Master II",
    "Master I",
  ],
  "destiny-2": [
    "Unranked",
    "Copper",
    "Bronze",
    "Silver",
    "Gold",
    "Platinum",
    "Adept",
    "Ascendant",
  ],
  "dota-2": [
    "Unranked",
    "Herald I",
    "Herald II",
    "Herald III",
    "Herald IV",
    "Herald V",
    "Guardian I",
    "Guardian II",
    "Guardian III",
    "Guardian IV",
    "Guardian V",
    "Crusader I",
    "Crusader II",
    "Crusader III",
    "Crusader IV",
    "Crusader V",
    "Archon I",
    "Archon II",
    "Archon III",
    "Archon IV",
    "Archon V",
    "Legend I",
    "Legend II",
    "Legend III",
    "Legend IV",
    "Legend V",
    "Ancient I",
    "Ancient II",
    "Ancient III",
    "Ancient IV",
    "Ancient V",
    "Divine I",
    "Divine II",
    "Divine III",
    "Divine IV",
    "Divine V",
    "Immortal",
  ],
  "world-of-warcraft": [
    "Unranked",
    "Combatant I",
    "Combatant II",
    "Challenger I",
    "Challenger II",
    "Rival I",
    "Rival II",
    "Duelist",
    "Elite",
    "Gladiator",
    "Rank One",
  ],
  "escape-from-tarkov": ["Unranked"],
  rust: ["Unranked"],
  "ea-sports-fc": [
    "Division 10",
    "Division 9",
    "Division 8",
    "Division 7",
    "Division 6",
    "Division 5",
    "Division 4",
    "Division 3",
    "Division 2",
    "Division 1",
    "Elite Division",
  ],
  "dead-by-daylight": [
    "Ash IV",
    "Ash III",
    "Ash II",
    "Ash I",
    "Bronze IV",
    "Bronze III",
    "Bronze II",
    "Bronze I",
    "Silver IV",
    "Silver III",
    "Silver II",
    "Silver I",
    "Gold IV",
    "Gold III",
    "Gold II",
    "Gold I",
    "Iridescent IV",
    "Iridescent III",
    "Iridescent II",
    "Iridescent I",
  ],
  "marvel-rivals": [
    "Bronze III",
    "Bronze II",
    "Bronze I",
    "Silver III",
    "Silver II",
    "Silver I",
    "Gold III",
    "Gold II",
    "Gold I",
    "Platinum III",
    "Platinum II",
    "Platinum I",
    "Diamond III",
    "Diamond II",
    "Diamond I",
    "Grandmaster III",
    "Grandmaster II",
    "Grandmaster I",
    "Celestial III",
    "Celestial II",
    "Celestial I",
    "Eternity",
    "One Above All",
  ],
} as const satisfies Record<string, readonly string[]>;

export const RANK_OPTIONS = Array.from(
  new Set(Object.values(GAME_RANKS).flat())
) as readonly string[];

export function getRankOptionsForGame(slug: string): readonly string[] {
  return GAME_RANKS[slug as keyof typeof GAME_RANKS] ?? RANK_OPTIONS;
}
